### ISSUE TITLE
Mechanism of scripts termination: improvements and documentation

### ISSUE THREAD

**Issue by selivan** [komarov/switchman#4]
It would be convinient to add options to control job termination: signal sent(default=SIGTERM) and pause before SIGKILL(0 = no SIGKILL at all). 

Also it would be useful to describe job termination process(signals sent, pause langth, if child processes are affected) in README.

**Comment by komarov** [comment]
Generally speaking, I can't see any problems with making this behaviour configurable, but a potential suppressing of SIGKILL somewhat concerns me.

Reliable termination (as reliable as it might be possible) of the child process is one of the key guarantees, which ideally shouldn't depend on the configuration.
In this sense I can totally see how configuring the graceful termination part is useful, but I wouldn't want to give up the right to SIGKILL in case that part fails.

If this was your point, then I totally support it.
If you have a suggestion on the configuration format I'd like to see it and learn more about your use cases.

Otherwise if I am completely missing some sensible use for suppressing SIGKILL here, please expand on it as well.

**Comment by selivan** [comment]
In my case switchman is used to control long-running scripts, performing heavy operations in NoSQL database, and unexpected script termination can lead to incinsistent data. So it's better to let script take as much time to finish, as it need. This can be done by suppressing SIGKILL ot by setting large enough timeout before it. So you are right, just ability to set timeout may be enough.

**Comment by komarov** [comment]
Please check dcdfd4d743e13edf5fbe783a8f7e5dff82c430a6
May I ask you to test it before I upload the new version to CPAN? Please let me know if it works for you.

**Comment by selivan** [comment]
I applied changes to /usr/share/perl5/App/Switchman.pm on installed switchman=1.07-1 and added termination_timeout option to /etc/switchman.conf - it seems to work fine

**Comment by selivan** [comment]
Build failed: 

Test Summary Report
-------------------
t/get_group_hosts.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.04 usr  0.01 sys +  0.08 cusr  0.01 csys =  0.14 CPU)
Result: FAIL
Failed 1/1 test programs. 0/0 subtests failed.
make[1]: *** [test_dynamic] Error 2

Btw, it can be useful to have build instructions in README.md

**Comment by selivan** [comment]
And second thought - it may be useful to terminate switchman with non-zero exit code, if timeout expired and it killed driven process by SIGKILL. So we can see, if script couldn't terminate gracefuly and was killed by force.

**Comment by komarov** [comment]
I think it is related to an old version of Test::More installed that doesn't understand `done_testing`, upgrading should help.

Ok then, I'll release 1.08 on CPAN this evening.
